server:
  port: 8802

spring:
  application:
    name: zipkinStream-client2
  zipkin:
    base-url: http://localhost:8801
  rabbitmq:
      host: 192.168.2.201
      port: 5672
      username: admin
      password: admin

